### ISSUE TITLE
maskMoney('unmasked') should return integer

### ISSUE THREAD

**Issue by adriandmitroca** [plentz/jquery-maskmoney#195]
In terms of good architecture, money values should be always stored as integers for precise calculation capabilities.

Mathematical operations on floats could generate unnecessary and unexpected behavior.

**Comment by gbass84** [comment]
How would you propose to do so given that money is frequently expressed in fractional values while an integer is a whole number?

**Comment by plentz** [comment]
so, how we return the unmasked value of "1.20"?

**Comment by adriandmitroca** [comment]
Pretty simple - as a 120. Integer. 

Of course when we output our value from the system we format it correctly in every possible format.

**Comment by gbass84** [comment]
Why not just shift the digits yourself? Masking is for human consumption, and while unmask does have a certain logic to reversing human readability, this plugin allows for varying levels of decimal accuracy, meaning that unmask would not return a universally meaningful value without packaging it with the field settings.

Consider the case where you have multiple masking accuracy settings on the same page, defined inline on the input. Returning an unmasked value would require reading the settings off of the input, and returning an object rather than a value, so that further processing can be done.

1.20 vs 1.200000 for instance.

**Comment by adriandmitroca** [comment]
You are probably right about the flexibility. Consider it closed.
